[wip] Change to buildsystem pybuild / disable dh_auto_clean
dh_auto_clean (and at least dh_auto_configure) dropped python-distutils as build
system (in compat 12) and use pybuild instead. Therefor switching the
build system to pybuild.

git buildpackage  / git-pbuilder fails to call dh_auto_clean (with and
without using pybuild):

  % gbp buildpackage --git-ignore-new --git-pbuilder --git-ignore-branch --git-dist=sid --git-arch=amd64
  gbp:info: Building with (cowbuilder) for sid:amd64
  Building with cowbuilder for distribution sid, architecture amd64
  + pdebuild --buildresult ../ --pbuilder cowbuilder --debbuildopts '' -- --architecture amd64 --basepath/var/cache/pbuilder/base-sid-amd64.cow
  W: /home/jkirk/.pbuilderrc does not exist
  I: using cowbuilder as pbuilder
  dpkg-checkbuilddeps: error: Unmet build dependencies: python3-setuptools python3-all
  W: Unmet build-dependency in source
  dpkg-source: info: applying interpreter
  dh clean --with bash-completion,python3 --buildsystem=pybuild
     dh_auto_clean -O--buildsystem=pybuild
          pybuild --clean -i python{version} -p 3.5
  I: pybuild base:184: python3.5 setup.py clean
  Traceback (most recent call last):
    File "setup.py", line 16, in <module>
      import setuptools
  ImportError: No module named 'setuptools'
  E: pybuild pybuild:283: clean: plugin distutils failed with: exit code=1: python3.5 setup.py clean
  dh_auto_clean: pybuild --clean -i python{version} -p 3.5 returned exit code 13
  debian/rules:8: recipe for target 'clean' failed
  make: *** [clean] Error 25
  gbp:error: 'git-pbuilder' failed: it exited with 2

  % gbp buildpackage --git-ignore-new --git-pbuilder --git-ignore-branch --git-dist=sid --git-arch=amd64
  gbp:info: Building with (cowbuilder) for sid:amd64
  Building with cowbuilder for distribution sid, architecture amd64
  + pdebuild --buildresult ../ --pbuilder cowbuilder --debbuildopts '' -- --architecture amd64 --basepath /var/cache/pbuilder/base-sid-amd64.cow
  W: /home/jkirk/.pbuilderrc does not exist
  I: using cowbuilder as pbuilder
  dpkg-checkbuilddeps: error: Unmet build dependencies: python3-setuptools python3-all
  W: Unmet build-dependency in source
  dh clean --with bash-completion,python3
     dh_auto_clean
  dh_auto_clean: Please use the third-party "pybuild" build system instead of python-distutils
  dh_auto_clean: This feature was removed in compat 12.
  debian/rules:7: recipe for target 'clean' failed
  make: *** [clean] Error 2
  gbp:error: 'git-pbuilder' failed: it exited with 2

Therefor disabling dh_auto_clean for now.